services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_lambda_s3
    ports:
      - "4566:4566"       # host:container edge port
    environment:
      - SERVICES=lambda,s3,stepfunctions,dynamodb
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - LS_LOG=debug
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_FLAGS=-m 256m
    networks:
      - lambda_s3_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./localstack-s3-data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

networks:
  lambda_s3_net:
    name: lambda_s3_net
