services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,s3,stepfunctions,dynamodb
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - LS_LOG=warn
      - LAMBDA_EXECUTOR=local
      - PERSISTENCE=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-s3-data:/var/lib/localstack"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  k6:
    image: grafana/k6:latest
    container_name: k6_runner
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    networks:
      - app_net
    volumes:
      - ./k6:/scripts
    depends_on:
      - localstack

networks:
  app_net:
    name: app_net
