name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Static Code Analysis
      run: |
        npm run lint
        npm audit

    - name: Run Unit Tests
      run: npm test

    - name: Setup LocalStack
      run: |
        pip install awscli-local
        docker-compose -f docker-compose.lambda-s3.yml up -d
        sh ./scripts/wait-for-services.sh
        node scripts/deploy-localstack.js

    - name: Run k6 Performance Tests
      run: |
        docker-compose -f docker-compose.lambda-s3.yml exec -T k6 sh -c "sh /app/run-k6-tests.sh"

    - name: Generate Consolidated Report
      run: |
        node scripts/generate-consolidated-report.js

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/consolidated/

  smoke-test:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Smoke Test
        run: npm run test:robust
